In [32]:
import pandas as pd
import numpy as np

In [33]:
#read xlsx with the sheet D2SMSA and columns are  the second row
df = pd.read_excel('D2SMSA.xlsx', sheet_name='D2SMSA', header=1)
df.head(5)

,id,land,populat,pcity,psen,nophy,nobed,highschgr,laborf,pinc,crime,reg,crime/pop
0,1,1384,9387,78.1,12.3,25627,69678,50.1,4083.9,72100,709234,1,75.554916
1,2,4069,7031,44.0,10.0,15389,39699,62.0,3353.6,52737,499813,4,71.087043
2,3,3719,7017,43.9,9.4,13326,43292,53.9,3305.9,54542,393162,2,56.029927
3,4,3553,4794,37.4,10.7,9724,33731,50.6,2066.3,33216,198102,1,41.322904
4,5,3916,4370,29.9,8.8,6402,24167,52.2,1966.7,32906,294466,2,67.383524

In [34]:
df = df[['crime/pop','nophy', 'nobed', 'highschgr', 'laborf', 'pinc']]
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

##### Are variables correlated to the crime/pop
We should remove nobed

##### Are variables correlated between themselves?
If we keep pinc we should remove laborf


Results 
Normal - 0.1979

Remove nobed - 0.1713

Remove laborf keep pinc - 0.1953

Remove pinc keep laborf - 0.1976

Remove nobed & laborf keep pinc - 0.1678

In [39]:
#do a vif analysis to see if there is any multicollinearity between the variables
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

X = add_constant(df[['nophy', 'nobed', 'highschgr', 'laborf', 'pinc']])
pd.Series([variance_inflation_factor(X.values, i) 
               for i in range(X.shape[1])], 
              index=X.columns)

const         58.283224
nophy         33.171839
nobed         25.652390
highschgr      1.126379
laborf       174.532432
pinc         252.775266
dtype: float64

#### only highschgr